portal:
  renameMoney: 0
  defaultLimit: 0
  maxLimit: 7
  limitToken: portalLimitToken
  limits:
    Peasant: 1
    Hireling: 1
    Merchant: 2
    Citizen: 2
    Knight: 3
    Noble: 4
    Lord: 4
    Aristocrate: 5
    Admin: -1
  renameItems:
    - ==: org.bukkit.inventory.ItemStack
      v: 1976
      type: MUSIC_DISC_CHIRP
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §9Lesser Aether Fragment
        lore:
          - A Lesser Aetherial Fragment
          - pulsating with magical energy.
          - §8Combine 5 Lesser Fragments
          - §8to gain a Common Fragment.
        custom-model-data: 2
  moveItems:
    - ==: org.bukkit.inventory.ItemStack
      v: 1976
      type: MUSIC_DISC_CHIRP
      amount: 3
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §9Lesser Aether Fragment
        lore:
          - A Lesser Aetherial Fragment
          - pulsating with magical energy.
          - §8Combine 5 Lesser Fragments
          - §8to gain a Common Fragment.
        custom-model-data: 2
stonecrusher:
  defaultLimit: -1
  limits:
    Peasant: -1
  stonesPerTick: 1
  lootTable:
    - input: STONE
      output:
        - item: lesserfragment
          chance: 0.1
        - item: GRAVEL
          chance: 0.9
    - input: COBBLESTONE
      output:
        - item: DIAMOND
          chance: 0.1
        - item: GRAVEL
          chance: 0.9
    - input: GRAVEL
      output:
        - item: DIAMOND
          chance: 0.1
trophyChest:
  featureItem: something
replicator:
  featureItem: replicator
  defaultLimit: -1
  limits:
    Peasant: -1
  excludedProducts:
    - ELYTRA
transmutationStation:
  featureItem: transmutationStation
spawnBlocker:
  featureItem: spawnBlocker
jukebox:
  featureItem: jukebox