name: CLFeatures
main: de.craftlancer.clfeatures.CLFeatures
api-version: 1.14
author: Syd Montague
version: ${project.version}
depend: [CLCore, Blueprints]
commands:
  portal:
    description: "Portal related commands"
    usage: /portal [list|name|move]
  pbook:
    description: "Portal Book related commands"
    usage: /pbook [add|select|remove]
  stonecrusher:
    description: "Stonecrusher related commands"
    usage: /stonecrusher [move]
  #  trophyChest:
  #    description: "TrophyChest related commands"
  #    usage: /trophyChest [move]
  replicator:
    description: "Replicator related commands"
    usage: /replicator [move|list]
  spawnBlocker:
    description: "SpawnBlocker related commands"
    usage: /spawnblocker [move|list]
  transmutationStation:
    description: "TransmutationStation related commands"
    usage: /transmutationstation [move|list]
  trophyDepositor:
    description: "TrophyDepositor related commands"
    usage: /trophyDepositor [move]
permissions:
  clfeature.portal.ignoreLimit:
    default: op
  clfeature.portal.book.add:
    default: true
  clfeature.portal.book.remove:
    default: true
  clfeature.portal.book.select:
    default: true
  clfeature.portal.book.get:
    default: true
  clfeature.portal.list.others:
    default: op
  clfeature.trophy.openothers:
    default: op
  clfeature.trophy.item.add:
    default: op
  clfeature.trophy.item.remove:
    default: op
  clfeature.trophy.item.list:
    default: op